name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checa o código do repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # Passo 2: Configura o JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Usando a distribuição do OpenJDK Temurin
        java-version: '17'

    # Passo 3: Cache do Maven para acelerar builds futuros
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Passo 4: Build e execução de testes
    - name: Build with Maven
      run: mvn clean install

    # Passo 5: Executa os testes
    - name: Run tests
      run: mvn test
